---
- hosts: wazuh test 
  become: true
  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - neofetch 
        state: latest
        update_cache: true
